name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Run Stryker.js mutation testing
        run: npx stryker run
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  # deploy:
  #   if: github.event_name == 'pull_request'
  #   runs-on: ubuntu-latest
  #   needs: build # Optional: make it depend on the build job
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Use Node.js 22
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '22.x'
  #         # cache: 'npm' # Not strictly necessary for this job if it doesn't run npm install

  #     - name: Make deploy script executable
  #       run: chmod +x scripts/deploy.sh

  #     - name: Execute deployment script
  #       run: ./scripts/deploy.sh github.head_ref github.sha # TODO: update deployment script to accept these parameters
